Refactor Phase01
Star-Academy/Winter99Co-Op-AmirMahdi-Kousheshi pull request #1
Opened 2021-02-08 04:42 UTC by amkamir82

2021-02-09 07:32 UTC, hoseinaghaei requested changes
you should change your interface name in order to, readers can understand the difference between interface and classes.

2021-02-09 08:29 UTC, hoseinaghaei requested changes
in the search function, you have several temporary variables that can be passed directly to each other.

2021-02-09 08:38 UTC, hoseinaghaei reviewed
you have 3 functions to find 3 kinds of input, therefore you loop three times, if you put them onto variable of the class, you can find three groups just with one loop and pass no parameter in functions like "subscriptionOfNoSignWords".

2021-02-09 08:43 UTC, hoseinaghaei requested changes
you must refactor the "finalCheck" function without any words, 40 lines dude!.

2021-02-09 08:51 UTC, hoseinaghaei reviewed
it should be better if you check the contain a word and get a list with other functions and just call them.

2021-02-09 12:31 UTC, amkamir82 commented
> you should change your interface name in order to, readers can understand the difference between interface and classes.

Done!

2021-02-13 22:16 UTC, mostmand requested changes

2021-02-13 22:16 UTC, mostmand commented on .idea/libraries/Maven__junit_junit_4_12.xml
> +<component name="libraryTable">
gitignore
مناسب اضافه شود تا فایل‌های 
.idea
کامیت نشوند. می‌توانید از سایت
gitignore.io
استفاده کنید

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/main/java/FileReader.java
> +    static FileSaving fileSaving;
بهتر است استاتیک نباشد

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/main/java/FileReader.java
>  public class FileReader {
این کلاس چه وظیفه‌ای دارد؟ صرفاً دارد کارها را به کلاس
FileSaving
واگذار می‌کند

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/main/java/FileSaving.java
> +    String path = "C:/Users/Amkam/Desktop/Folder";
آدرس بهتر است به جای هاردکد بودن از یک فایل کانفیگ خوانده شود

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/main/java/HashInvertedIndex.java
> +        for (File allFile : FileReader.getAllFiles()) {
نام متغیر
allFile
مناسب نیست شاید خود
file
بهتر باشد

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/main/java/HashInvertedIndex.java
> +            for (String s : input) {
حلقه‌ی داخلی می‌تواند یک تابع شود تا
indentation
کم شود

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/main/java/HashInvertedIndex.java
> +        if (wordLocations.containsKey(normalizeWord.toLowerCase())) {
می‌توان یک متغیر تعریف کرد و
normalizeWord.toLowerCase()
را در آن ذخیره کرد

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/main/java/HashInvertedIndex.java
> +        if (wordLocations.containsKey(normalizeWord.toLowerCase())) {
می‌توان کد را این گونه تغییر داد:
```java
String normalizedWord = stringSepartation.normalize(word).toLower();
if (!wordLocations.containsKey(normalizedWord)){
    wordLocations.put(normalizedWord, new ArrayList<String>());
}

ArrayList<String> locations = wordLocations.get(normalizedWord);
if (!locations .contains(docID)) { 
   locations.add(docID);
}
```

هر چند بهتر است به جای 
ArrayList<String>
از
HashSet<String>
استفاده شود تا تابع
contains()
سریع‌تر باشد

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/main/java/HashInvertedIndex.java
> +        ArrayList<String> checker = new ArrayList<>();
این تابع و تابع پایینی به نظر بیش از حد پیچیده شده و به نظرم اشکال منطقی هم داره

به نظرم صرفاً داکیومنت‌هایی رو برمی‌گردونه که اولین کلمه‌ی بدون علامت درشون هست

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/main/java/HashInvertedIndex.java
> +    private ArrayList<String> checkSubscriptionForNoSignWords(ArrayList<String> noSignWords) {
اسم تابع چندان گویا نیست که چی کار داره انجام میده

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/main/java/HashInvertedIndex.java
> +        checker.clear();
در چنین جاهایی بهتره که متغیر جدید استفاده بشه به جای این که از همون متغیر قبلی استفاده بشه

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/main/java/HashInvertedIndex.java
> +    private ArrayList<String> firstFinalCheckCondition(ArrayList<String> plusSignWordsDocs, ArrayList<String> minusSignWordsDocs, ArrayList<String> minusSignWords) {
اسم تابع‌ها مناسب نیست
first , third
اصلا گویا نیستن

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/main/java/HashInvertedIndex.java
> +        } else if (plusSignWordsDocs.size() != 0) {
وقتی کلاز بالایی
return
می‌کنه دیگه نیازی به استفاده از کلمه کلیدی
else
نیست

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/main/java/Main.java
> +            public String normalize(String word) {
پیاده سازی این توابع چرا توی یه کلاس اسم‌دار نیست که
StringSeparation
رو
Implement
می‌کنه؟

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/main/java/Main.java
> +            public String normalize(String word) {
در ضمن نام
StringSeparator
مناسب‌تر است تا
StringSeparation

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/main/java/Main.java
> +                    } else {
می‌تونه
else
با
if پایینش
ترکیب بشه، بشه
else if

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/test/java/FileReaderTest.java
> +public class FileReaderTest {
کاش برای تست برنچ مجزا می‌زدی که با کدهای ریفکتور از هم جدا باشن
ایشالا فازهای بعد رو مجزا پول ریکوئست بزن

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/test/java/FileReaderTest.java
> +        Assert.assertEquals(allFiles, FileReader.getAllFiles());
این
FileReader
با
fileReaderی
که بالا تعریف شده فرق داره و من نمیدونم اون بالایی اصلا برا چی تعریف شده

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/test/java/HashInvertedIndexTest.java
> +                ArrayList<String> strings = new ArrayList<>();
این قسمت به نظر تکراریه و توی پیاده سازی اصلی هم همینه

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/test/java/FileReaderTest.java
> +        String path = "C:/Users/Amkam/Desktop/Folder";
فایل‌هایی که برای تست مورد استفاده قرار می‌گیرند باید یه جایی کنار پروژه باشن و روی گیت هم پوش بشن تا اجرای اتوماتیک تست‌ها روی سرور دچار مشکل نشه هم چنین اگه یه توسعه دهنده‌ی دیگه کد رو کلون کرد بتونه تستا رو به درستی ران کنه

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/test/java/HashInvertedIndexTest.java
> +        List<String> expectedValues = Arrays.asList("2.txt");
بهتره سه تا تست بشه یا بهتر از اون استفاده از 
Parameterized test
هست

2021-02-13 22:16 UTC, mostmand commented on Phase01-Search/src/test/java/HashInvertedIndexTest.java
> +        List<String> expectedValues = Arrays.asList("2.txt");
لازم به ذکره که هر تست تنها یه چیز رو باید تست کنه

2021-02-14 16:26 UTC, mostmand commented on Phase01-Search/src/test/java/HashInvertedIndexTest.java
> +    public void searchThirdTest() {
چون کد این چند تا تست مشترکه می‌تونی از
parameterized test
استفاده کنی

2021-02-14 16:31 UTC, mostmand commented on Phase01-Search/src/main/java/HashInvertedIndex.java
> +            if (signWordsDocs.size() != 0) {
این تابع خیلی
indentation
داره بهتره داخل هر یک از اسکوپ‌هات یه تابع مجزا بشه
در ضمن اگه به جای این که
finalDocs
رو داخل هر یک از این اسکوپ‌ها تعریف کنی و ریترنش کنی قشنگ‌تره

2021-02-14 16:33 UTC, mostmand commented on Phase01-Search/src/main/java/Main.java
> +        while (true) {
این حلقه چی کار می‌کنه به نظر می‌رسه داخل حلقه فقط یه بار اجرا میشه

2021-02-14 16:35 UTC, mostmand commented on Phase01-Search/src/main/java/StringSeparatorImpl.java
> +            } else {
می‌تونه به جای
```java
else {
    if (...){
    }
}
```
بشه
```java
else if (...) {
    ...
}
```

2021-02-14 16:36 UTC, amkamir82 commented on Phase01-Search/src/main/java/Main.java
> +        while (true) {
این حلقه آدرسی که کاربر برای فولدرش میده رو میره با استفاد از یه فایل  چک میکنه اگه ادرس اشتباه باشه و فولدری نباشه میگه که ادرس اشتباهه و منتظر میمونه تا کاربر باز ادرس بده اگرم درست باشه ادرسو پاس میده برا برای کلای فایل سیوینگ تا کاراش انجام شه

2021-02-14 16:37 UTC, mostmand commented on Phase01-Search/src/main/java/HashInvertedIndex.java
> +        if (wordLocations.containsKey(normalizeWord.toLowerCase())) {
می‌تونی از هش‌ست استفاده کنی که هم سریع‌تره هم دیگه چک کردن شرط
```java
!locations.contains(docId)
```
رو لازم نداره.

2021-02-14 16:41 UTC, mostmand approved these changes
در کل اوکی بود فقط یکی دو تا کامنت گذاشتم یه نگاه بهشون بنداز

2021-02-14 16:43 UTC, mostmand commented
تستا هم کم بود تعدادش البته فکر کنم اونو یه برنچ دیگه داری می‌زنی درسته؟

2021-02-14 16:45 UTC, amkamir82 commented
> تستا هم کم بود تعدادش البته فکر کنم اونو یه برنچ دیگه داری می‌زنی درسته؟

نه من یه تست زدم بعد کاورج رو نگاه کردم دیدم 100 درصد کلاسام به جز مین کاور شدن گفتم دیگه فردا بپرسم ازتون که چکار کنم

2021-02-16 13:14 UTC, merged