Phase04 c#
Star-Academy/Winter99Co-Op-AmirMahdi-Kousheshi pull request #3
Opened 2021-02-18 09:48 UTC by amkamir82

2021-02-20 07:23 UTC, amirarab888 commented on Phase04-C#/Average/ConsoleApp1/Course.cs
> +            Student.AddCourseForStudent(studentNumber, this);
فکر کنم درست نباشه این جا کورس رو به 
student 
اضافه کنی

2021-02-20 07:48 UTC, amirarab888 requested changes

2021-02-20 07:48 UTC, amirarab888 commented on Phase04-C#/Average/ConsoleApp1/Course.cs
> +            Student.AddCourseForStudent(studentNumber, this);
یه جا دیگه باید این اتفاق بیفته

2021-02-20 07:48 UTC, amirarab888 commented on Phase04-C#/Average/ConsoleApp1/FileReader.cs
> +    interface FileReader
اول اسم 
interface 
باید حرف
I
باشه

2021-02-20 07:48 UTC, amirarab888 commented on Phase04-C#/Average/ConsoleApp1/FileReader.cs
> +        string path1 { get; set; }
اسم بهتری نمی شد؟

2021-02-20 07:48 UTC, amirarab888 commented on Phase04-C#/Average/ConsoleApp1/FileReaderImpl.cs
> +            this.path1 = path1;
چرا تو 
constructor 
این کارو کردی؟
تو موقع کال کردن تابع بهتر نبود؟

2021-02-20 07:48 UTC, amirarab888 commented on Phase04-C#/Average/ConsoleApp1/FileReaderImpl.cs
> +            var input = File.ReadAllText(path);
اسم بهتری نمی شد به جای 
input 
بزاری

2021-02-20 07:48 UTC, amirarab888 commented on Phase04-C#/Average/ConsoleApp1/FileReaderImpl.cs
> +            return JsonConvert.DeserializeObject<List<Student>>(input);
نوع داده های درون لیست رو نمیشد اینترفیس بزاری که عمومی تر باشه؟

2021-02-20 07:48 UTC, amirarab888 commented on Phase04-C#/Average/ConsoleApp1/Student.cs
> +            AllStudents.Add(this);
فکر نکنم جالب باشه که 
AllStudents
تو این کلاس باشه و همینجا هم بهش ادد بشه
شاید یه کنترلر باشه بهتره

2021-02-20 07:48 UTC, amirarab888 commented on Phase04-C#/Average/ConsoleApp1/Student.cs
> +            this.CalculateAverage();
محاسبه 
average
نباید این جا کال بشه شاید

2021-02-20 07:48 UTC, amirarab888 commented on Phase04-C#/Average/ConsoleApp1/Student.cs
> +        }
شاید بهتر باشه که استاتیک نباشه تا مشکل سینکرونایز و اینا پیش نیاد
و این که استیودنت رو بگیری بعد بهش یه 
course
اضافه کنی فک نکنم جالب باشه

2021-02-20 07:48 UTC, amirarab888 commented on Phase04-C#/Average/xunit-test/UnitTest1.cs
> +    public class UnitTest1
اسم جالب تر نمشد؟

2021-02-20 07:48 UTC, amirarab888 commented on Phase04-C#/Average/xunit-test/UnitTest1.cs
> +
اگر تابع 
equals
رو برای کلاس 
student 
اورراید میکردی بعد یه 
student 
میساختی با یه تابع تست این قضیه حل میشد

2021-02-20 07:48 UTC, amirarab888 commented on Phase04-C#/Average/xunit-test/UnitTest1.cs
> +}
چرا این تست ها تو یه کلاس جدا نیستن

2021-02-20 07:48 UTC, amirarab888 commented on Phase04-C#/Average/xunit-test/UnitTest1.cs
> +
چرا از ماک استفاده نکردی ؟ که از
de[endency
خلاص باشه تستت؟

2021-02-20 07:48 UTC, amirarab888 commented on Phase04-C#/Average/xunit-test/UnitTest1.cs
> +            Assert.Equal(student, topStudents[0]);
چرا کل لست رو بررسی نکردی؟

2021-02-20 07:48 UTC, amirarab888 commented on Phase04-C#/Average/xunit-test/UnitTest1.cs
> +}
شاید بهتر بود دیسریالایز کردن و خودن از فایل و اینا رو تست میکرید

2021-02-20 08:25 UTC, amkamir82 commented on Phase04-C#/Average/ConsoleApp1/FileReaderImpl.cs
> +            this.path1 = path1;
موقع کال کردن بهش میدم ، اینجا ست میشه

2021-02-20 08:26 UTC, amkamir82 commented on Phase04-C#/Average/xunit-test/UnitTest1.cs
> +    public class UnitTest1
تست تکیمل نشده هنوز یه نسخه دمو هست این

2021-02-26 21:36 UTC, saj76 commented on Phase04-C#/Average/ConsoleApp1/Student.cs
> +        public static List<Student> AllStudents = new List<Student>();
این جاش اینجا نیست میتونی ببری توی کلاس
Program 
حتی

2021-02-26 21:37 UTC, saj76 commented on Phase04-C#/Average/ConsoleApp1/Student.cs
> +        public static List<Student> AllStudents = new List<Student>();
حالا چرا استاتیک اصلا

2021-02-26 21:38 UTC, saj76 commented on Phase04-C#/Average/ConsoleApp1/Student.cs
> +        private static Student GetStudentByStudentNumber(int studentNumber)
کلا این توابع جاشون نیست 
توی کلاس جدید میتونی ببریشون

2021-02-28 09:02 UTC, amkamir82 commented on Phase04-C#/Average/ConsoleApp1/Student.cs
> +        private static Student GetStudentByStudentNumber(int studentNumber)
آخه مگه اینا مرتبط به کلاس استیودنت نیستن؟

2021-02-28 10:16 UTC, mostmand requested changes

2021-02-28 10:16 UTC, mostmand commented on Phase04-C#/Average/.vs/Average/v16/lut/0/b/Average/Debug/netcoreapp3.1/Average.deps.json
> +{
این همه فایل نامربوط چرا به گیت اضافه شده اند؟

2021-02-28 10:16 UTC, mostmand commented on Phase04-C#/Average/ConsoleApp1/FileReaderImpl.cs
> +            this.path1 = path1;
بهتره توی ورودی تابع گرفته بشه

2021-02-28 10:16 UTC, mostmand commented on Phase04-C#/Average/ConsoleApp1/IFileReader.cs
> +        string path { get; set; }
بهتره تو ورودی تابع‌ها گرفته بشه به جای این که این جا باشه

2021-02-28 10:16 UTC, mostmand commented on Phase04-C#/Average/ConsoleApp1/IFileReader.cs
> +        string path { get; set; }
path , path1

2021-02-28 10:16 UTC, mostmand commented on Phase04-C#/Average/ConsoleApp1/IFileReader.cs
> +        string path1 { get; set; }
نام‌گذاری مناسب نیست
path1
اصلا گویا نیست

2021-02-28 10:16 UTC, mostmand commented on Phase04-C#/Average/ConsoleApp1/Program.cs
> +        public static string path = "C://Users/Amkam/Desktop/Students.json";
بهتر است فایل‌های جیسون روی ریپو قرار بگیرند و آدرس‌ها به صورت نسبی داده شود

2021-02-28 10:16 UTC, mostmand commented on Phase04-C#/Average/ConsoleApp1/Student.cs
> +            foreach (var course in this.Courses)
میشه از
Linq
استفاده کرد برای محاسبه‌ی معدل

2021-02-28 10:16 UTC, mostmand commented on Phase04-C#/Average/xunit-test/UnitTest1.cs
> +{
کلاس خالی پاک شود یا تکمیل شود

2021-02-28 10:16 UTC, mostmand commented
نکاتی که بچه‌ها گفته بودن هم نکات خوبی بود من دیگه تکرار نکردم

2021-03-01 12:31 UTC, mostmand requested changes

2021-03-01 12:31 UTC, mostmand commented on Phase04-C#/Average/ConsoleApp1/Student.cs
> +        static StudentController controller = new StudentController();
بهتر از قبل شد ولی باز هم متوجه نمیشم چرا کلاس
Stduent
باید
StudentController
داشته باشه و وظیفه‌ی
AddCourse
توی کلاس
Student
باشه؟

2021-03-01 21:11 UTC, saj76 commented on Phase04-C#/Average/ConsoleApp1/Student.cs
> +        private static Student GetStudentByStudentNumber(int studentNumber)
نه دیگه کلاس
Student
که وظیفه اش نگه داری از آبجکت های خودش نیست

2021-03-02 07:57 UTC, mostmand approved these changes
احسنت عالی

2021-03-02 09:59 UTC, merged